export enum DurationEnum {
  ONE_MONTH = '1',
  TWO_MONTHS = '2',
  THREE_MONTHS = '3',
  FOUR_MONTHS = '4',
  FIVE_MONTHS = '5',
  SIX_MONTHS = '6',
  SEVEN_MONTHS = '7',
  EIGHT_MONTHS = '8',
  NINE_MONTHS = '9',
  TEN_MONTHS = '10',
  ELEVEN_MONTHS = '11',
  ONE_YEAR = '12',
  TWO_YEARS = '24',
  THREE_YEARS = '36',
  FOUR_YEARS = '48',
  FIVE_YEARS = '60',
  SIX_YEARS = '72',
  SEVEN_YEARS = '84',
  EIGHT_YEARS = '96',
  NINE_YEARS = '108',
  TEN_YEARS = '120',
}
