export enum EventsEnum {
  USER_CREATED = 'user/created',
  USER_UPDATED = 'user/updated',
  USER_DELETED = 'user/deleted',
  USER_BANNED = 'user/banned',
  USER_UNBANNED = 'user/unbanned',
  USER_ADDED_ORGANIZATION_ACCESS = 'user/organization/access/added',
  USER_REMOVED_ORGANIZATION_ACCESS = 'user/organization/access/removed',
  USER_LOCKED = 'user/locked',
  USER_CREDIT_BALANCE_UPDATED = 'user/credit-balance/updated',
  USER_UNLOCKED = 'user/unlocked',
  USER_PASSWORD_UPDATED = 'user/password/updated',
  USER_EMAIL_UPDATED = 'user/email/updated',
  USER_CURRENCY_UPDATED = 'user/currency/updated',
  USER_INVOICE_CONTACT_UPDATED = 'user/invoice-contact/updated',
  USER_POLICY_UPDATED = 'user/policy/updated',
  USER_LANGUAGES_UPDATED = 'user/languages/updated',
  USER_CUSTOM_PRICE_POLICIES_UPDATED = 'user/custom-price-policies/updated',
  USER_CUSTOM_ADDON_PRICE_POLICIES_UPDATED = 'user/custom-addon-price-policies/updated',
  USER_CUSTOM_AFFILIATE_ADDED = 'user/custom-affiliate/added',
  USER_CUSTOM_AFFILIATE_REMOVED = 'user/custom-affiliate/removed',
  USER_INVOICE_INTERVAL_UPDATED = 'user/invoice-interval/updated',
  USER_ADDITIONAL_NOTIFICATION_EMAIL_REMOVED = 'user/additional-notification-email/removed',
  USER_ADDITIONAL_NOTIFICATION_EMAIL_ADDED = 'user/additional-notification-email/added',
  USER_COMMENT_ADDED = 'user/comment/added',
  USER_COMMENT_REMOVED = 'user/comment/removed',
  USER_COMMENT_UPDATED = 'user/comment/updated',
  USER_TAGS_UPDATED = 'user/tags/updated',
  USER_SETTING_ADDED = 'user/setting/added',
  USER_SETTING_REMOVED = 'user/setting/removed',
  USER_SETTING_UPDATED = 'user/setting/updated',
  USER_START_SELLING = 'user/start-selling',
  USER_ROLES_UPDATED = 'user/roles/updated',

  MESSAGE_CREATED = 'message/created',
  MESSAGE_UPDATED = 'message/updated',
  MESSAGE_DELETED = 'message/deleted',

  NOTIFICATION_SENT = 'notification/sent',

  POLICY_CREATED = 'policy/created',
  POLICY_UPDATED = 'policy/updated',
  POLICY_DELETED = 'policy/deleted',

  PRODUCT_CATEGORY_CREATED = 'product-category/created',
  PRODUCT_CATEGORY_UPDATED = 'product-category/updated',
  PRODUCT_CATEGORY_DELETED = 'product-category/deleted',

  INVOICE_CONTACT_CREATED = 'invoice-contact/created',
  INVOICE_CONTACT_UPDATED = 'invoice-contact/updated',
  INVOICE_CONTACT_DELETED = 'invoice-contact/deleted',

  INVOICE_CREATED = 'invoice/created',
  INVOICE_UPDATED = 'invoice/updated',
  INVOICE_DELETED = 'invoice/deleted',

  CURRENCY_CREATED = 'currency/created',
  CURRENCY_UPDATED = 'currency/updated',
  CURRENCY_DELETED = 'currency/deleted',

  AFFILIATE_CREATED = 'affiliate/created',
  AFFILIATE_UPDATED = 'affiliate/updated',
  AFFILIATE_DELETED = 'affiliate/deleted',

  COMPANY_CREATED = 'company/created',
  COMPANY_UPDATED = 'company/updated',
  COMPANY_DELETED = 'company/deleted',
  COMPANY_PROVIDER_ATTACHED = 'organization/service-provider/attached',
  COMPANY_PROVIDER_DETACHED = 'organization/service-provider/detached',

  TLD_CREATED = 'tld/created',
  TLD_UPDATED = 'tld/updated',
  TLD_DELETED = 'tld/deleted',

  SERVICE_PROVIDER_CREATED = 'service-provider/created',
  SERVICE_PROVIDER_UPDATED = 'service-provider/updated',
  SERVICE_PROVIDER_DELETED = 'service-provider/deleted',
  SERVICE_PROVIDER_INSTALLED = 'service-provider/installed',
  SERVICE_PROVIDER_UNINSTALLED = 'service-provider/uninstalled',

  DOMAIN_CONTACT_CREATED = 'domain-contact/created',
  DOMAIN_CONTACT_UPDATED = 'domain-contact/updated',
  DOMAIN_CONTACT_DELETED = 'domain-contact/deleted',

  DOMAIN_CATEGORY_CREATED = 'domain-category/created',
  DOMAIN_CATEGORY_UPDATED = 'domain-category/updated',
  DOMAIN_CATEGORY_DELETED = 'domain-category/deleted',

  ADDON_CREATED = 'addon/created',
  ADDON_UPDATED = 'addon/updated',
  ADDON_DELETED = 'addon/deleted',

  PAYMENT_CREATED = 'payment/created',
  PAYMENT_CANCELED = 'payment/canceled',
  PAYMENT_FAILED = 'payment/failed',
  PAYMENT_SUBSCRIBED = 'payment/subscribed',
  PAYMENT_UNSUBSCRIBED = 'payment/unsubscribed',
  PAYMENT_UPDATED = 'payment/updated',
  PAYMENT_DELETED = 'payment/deleted',
  PAYMENT_COMPLETED = 'payment/completed',

  TEMPLATE_CREATED = 'template/created',
  TEMPLATE_UPDATED = 'template/updated',
  TEMPLATE_DELETED = 'template/deleted',

  COUPON_CREATED = 'coupon/created',
  COUPON_UPDATED = 'coupon/updated',
  COUPON_DELETED = 'coupon/deleted',

  TEMPLATE_PROVIDER_CREATED = 'template-provider/created',
  TEMPLATE_PROVIDER_UPDATED = 'template-provider/updated',
  TEMPLATE_PROVIDER_DELETED = 'template-provider/deleted',

  ORDER_CREATED = 'order/created',
  ORDER_STATUS_INPROGRESS = 'order/status/in-progress',
  ORDER_STATUS_COMPLETED = 'order/status/completed',
  ORDER_STATUS_CANCELED = 'order/status/canceled',
  ORDER_STATUS_REFUNDED = 'order/status/refunded',
  ORDER_INSUFFICIENT_BALANCE = 'order/insufficient-balance',
  ORDER_DELETED = 'order/deleted',

  SETTING_CREATED = 'setting/created',
  SETTING_UPDATED = 'setting/updated',
  SETTING_DELETED = 'setting/deleted',

  ISSUE_CREATED = 'issue/created',
  ISSUE_UPDATED = 'issue/updated',
  ISSUE_DELETED = 'issue/deleted',

  TASK_CREATED = 'task/created',
  TASK_UPDATED = 'task/updated',
  TASK_DELETED = 'task/deleted',
  TASK_CANCELED = 'task/canceled',
  TASK_INPROGRESS = 'task/in-progress',
  TASK_COMPLETED = 'task/completed',
  TASK_UPDATE_PERCENTAGE = 'task/percentage/updated',

  PRODUCT_CREATED = 'product/created',
  PRODUCT_UPDATED = 'product/updated',
  PRODUCT_DELETED = 'product/deleted',
  PRODUCT_AUTO_RENEW_UPDATED = 'product/auto-renew/updated',
  PRODUCT_ENABLED = 'product/enabled',
  PRODUCT_DISABLED = 'product/disabled',

  IP_GROUP_CREATED = 'ip-group/created',
  IP_GROUP_UPDATED = 'ip-group/updated',
  IP_GROUP_DELETED = 'ip-group/deleted',

  IP_CREATED = 'ip/created',
  IP_UPDATED = 'ip/updated',
  IP_DELETED = 'ip/deleted',

  DOMAIN_NAME_CREATED = 'domain-name/created',
  DOMAIN_NAME_UPDATED = 'domain-name/updated',
  DOMAIN_NAME_DELETED = 'domain-name/deleted',
  DOMAIN_NAME_LOCKED = 'domain-name/locked',
  DOMAIN_NAME_UNLOCKED = 'domain-name/unlocked',
  DOMAIN_NAME_SHIELD_ACTIVATED = 'domain-name/idshield-activated',
  DOMAIN_NAME_SHIELD_DEACTIVATED = 'domain-name/idshield-deactivated',
  DOMAIN_NAME_BUNDLE_ADDED = 'domain-name/bundle-added',
  DOMAIN_NAME_BUNDLE_REMOVED = 'domain-name/bundle-removed',
  DOMAIN_NAME_REGISTRANT_UPDATED = 'domain-name/registrant-updated',
  DOMAIN_NAME_ADMIN_UPDATED = 'domain-name/admin-updated',
  DOMAIN_NAME_TECH_UPDATED = 'domain-name/tech-updated',
  DOMAIN_NAME_BILLING_UPDATED = 'domain-name/billing-updated',
  DOMAIN_NAME_ADDITIONAL_UPDATED = 'domain-name/additional-updated',

  ITEM_CREATED = 'item/created',
  ITEM_UPDATED = 'item/updated',
  ITEM_DELETED = 'item/deleted',
  ITEM_IP_ATTACHED = 'item/ip-attached',
  ITEM_IP_DETACHED = 'item/ip-detached',
  ITEM_DETACHED_FROM_ORDER = 'item/detached-from-order',
  ITEM_POSTPONED = 'item/postponed',
  ITEM_TRANSFERRED_IN = 'item/transferred-in',
  ITEM_CANCELED = 'item/canceled',
  ITEM_SUSPENDED = 'item/suspended',
  ITEM_AFFILIATE_ADDED = 'item/affiliate/added',
  ITEM_BUNDLE_ATTACHED = 'item/bundle/attached',
  ITEM_BUNDLE_DETACHED = 'item/bundle/detached',
  ITEM_SET_INACTIVE = 'item/set-inactive',
  ITEM_PROCESSED = 'item/processed',

  ORDER_PAID = 'order/paid',
}
